FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y gcc rust cargo

COPY ./src .
COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT ["/bin/bash"]